channels:
  - conda-forge
  - defaults
dependencies:
  - scikit-learn<1.6
  - pandas 
  - numpy
  - pyarrow
  - pytest
  - sympy
  - pyyaml
  - pip 
  - pip:
    - git+https://github.com/EpistasisLab/pmlb # mislabeled datasets fixed
    - pytest-order
