name: eql
channels:
    - conda-forge
dependencies:
    - python=3.10
    - pip
    - numpy
    - sympy
    - jax>=0.4.26
    - jaxlib>=0.4.26
    - scikit-learn
    - scipy
    - flax>=0.8.0
    - optax>=0.2.0
    - pyyaml
    - pandas
